# Generated by Django 3.1.7 on 2021-04-09 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210410_0341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='amount',
            new_name='Amount',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='img',
            new_name='Image',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='Title',
        ),
    ]
